"use client";

/**
 * AskAI — trade-facing AI chat widget.
 *
 * Ported from the Mission Control prototype's AskAI with three
 * adaptations:
 * - Visual language uses Chekku's emerald accent + light/dark CSS
 *   variables, not MC's CoreTechX cyan
 * - Three sizes (compact, default, prominent) so Home can run a
 *   prominent input while Find Jobs / Job detail run smaller variants
 * - Responses render with the same lightweight markdown formatter as
 *   MC's version (bold, bullets, numbered lists, headings)
 *
 * Operates as either a controlled chat UI (input + ask + history) or
 * a one-shot via the `trigger` prop. Suggestion chips fire questions
 * directly without going through the input.
 */

import { useEffect, useRef, useState } from "react";

// ─── Markdown renderer ───────────────────────────────────────────────
function FormatAI({ text }: { text: string }) {
  const renderInline = (s: string) =>
    s.split(/(\*\*[^*]+\*\*)/g).map((p, i) =>
      p.startsWith("**") && p.endsWith("**") ? (
        <strong key={i} className="font-semibold text-foreground">
          {p.slice(2, -2)}
        </strong>
      ) : (
        p
      ),
    );

  const lines = text.split("\n");
  const out: React.ReactNode[] = [];
  let bullets: string[] = [];
  let numbered: string[] = [];

  const flushBullets = () => {
    if (bullets.length) {
      out.push(
        <ul
          key={out.length}
          className="my-1 list-inside list-disc space-y-0.5 pl-1"
        >
          {bullets.map((b, i) => (
            <li key={i}>{renderInline(b)}</li>
          ))}
        </ul>,
      );
      bullets = [];
    }
  };
  const flushNumbered = () => {
    if (numbered.length) {
      out.push(
        <ol
          key={out.length}
          className="my-1 list-inside list-decimal space-y-0.5 pl-1"
        >
          {numbered.map((n, i) => (
            <li key={i}>{renderInline(n)}</li>
          ))}
        </ol>,
      );
      numbered = [];
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      flushBullets();
      flushNumbered();
      continue;
    }
    if (/^#{1,3}\s/.test(line)) {
      flushBullets();
      flushNumbered();
      out.push(
        <p key={out.length} className="mt-2 mb-0.5 font-semibold">
          {renderInline(line.replace(/^#{1,3}\s/, ""))}
        </p>,
      );
    } else if (/^[-*•]\s+/.test(line)) {
      flushNumbered();
      bullets.push(line.replace(/^[-*•]\s+/, ""));
    } else if (/^\d+\.\s+/.test(line)) {
      flushBullets();
      numbered.push(line.replace(/^\d+\.\s+/, ""));
    } else {
      flushBullets();
      flushNumbered();
      out.push(
        <p key={out.length} className="my-0.5 leading-relaxed">
          {renderInline(line)}
        </p>,
      );
    }
  }
  flushBullets();
  flushNumbered();
  return <>{out}</>;
}

// ─── Component ───────────────────────────────────────────────────────

export interface AskAISuggestion {
  label: string;
  question: string;
}

export interface AskAIProps {
  /**
   * Context string injected into the system prompt — describes Brett's
   * relevant state for this surface (today's jobs, current job
   * details, opportunity board summary, etc.). Generated by the
   * per-surface context generators in /lib/ai/contexts.ts.
   */
  context: string;
  /**
   * Visual size:
   * - "prominent" — Home's primary AI surface
   * - "default" — Find Jobs / Job detail / etc.
   * - "compact" — slot-in usage
   */
  size?: "prominent" | "default" | "compact";
  placeholder?: string;
  suggestions?: AskAISuggestion[];
  /**
   * EH-discipline pattern (Phase 6): when true, suggestion chips are
   * hidden at rest and only appear when the input is focused or the
   * conversation is non-empty. Keeps the surface visually calm while
   * preserving instant typing.
   */
  collapsibleChips?: boolean;
  /**
   * Phase 7 change 5: when true, the AI card uses an accent-tinted
   * background and shows a "Chekku AI" badge in the corner. Makes
   * the AI surface visually distinct from regular floating cards.
   * Used on Home where AI is the primary surface element.
   */
  distinctive?: boolean;
  /** Fire a one-shot question by setting trigger.text and bumping nonce. */
  trigger?: { text: string; nonce: number };
}

export default function AskAI({
  context,
  size = "default",
  placeholder,
  suggestions,
  collapsibleChips = false,
  distinctive = false,
}: AskAIProps) {
  const [q, setQ] = useState("");
  const [msgs, setMsgs] = useState<{ role: string; content: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [focused, setFocused] = useState(false);
  const tail = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (msgs.length > 0)
      tail.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [msgs]);

  const ask = async (override?: string) => {
    const u = (override ?? q).trim();
    if (!u || loading) return;
    if (!override) setQ("");
    setMsgs((m) => [...m, { role: "user", content: u }]);
    setLoading(true);
    const sys = `You are Chekku — the trade-facing AI assistant for Circl, an Australian platform that allocates installation and repair work to qualified trades. You are helping a tradesperson on-the-go via a mobile app. Be direct, practical, and warm — they're often on site, sometimes between jobs, and they need answers, not preambles. Australian context throughout (NSW Fair Trading licences, ATO/GST, BAS quarters, Aussie suburbs). Avoid jargon. Cap responses at ~150 words unless the question genuinely needs a longer breakdown.

If the trade asks about contacting Circl Support or messaging the customer, draft the message they should send and clearly mark it as a draft for them to review and send themselves — do not claim to have sent anything. The trade reviews and sends manually.

If a question can't be answered from the context provided, say so directly and suggest the right place to look (e.g. "your job detail screen has the equipment tracking number"). Don't invent details.

Trade context:
${context}`;
    let reply: string;
    try {
      const res = await fetch("/api/anthropic", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-5",
          max_tokens: 1000,
          system: sys,
          messages: [
            ...msgs.map((m) => ({ role: m.role, content: m.content })),
            { role: "user", content: u },
          ],
        }),
      });
      const d = await res.json();
      const text = d?.content?.find(
        (b: { type: string; text: string }) => b.type === "text",
      )?.text;
      if (text) {
        reply = text;
      } else {
        const apiErr = d?.error?.message ?? d?.error ?? `HTTP ${res.status}`;
        const apiType = d?.error?.type ? ` (${d.error.type})` : "";
        reply = `⚠ AI error${apiType}: ${apiErr}`;
        console.error("AskAI: API returned non-content response", d);
      }
    } catch (e) {
      reply = `⚠ Could not reach /api/anthropic — ${e instanceof Error ? e.message : "network error"}`;
      console.error("AskAI: fetch threw", e);
    }
    setMsgs((m) => [...m, { role: "assistant", content: reply }]);
    setLoading(false);
  };

  // Sizing
  const inputPadY = size === "prominent" ? "py-3" : "py-2.5";
  const askPadX = size === "prominent" ? "px-5" : "px-4";
  const askPadY = size === "prominent" ? "py-3" : "py-2.5";
  const askText = size === "prominent" ? "text-[15px]" : "text-[14px]";
  const inputText = size === "prominent" ? "text-[15px]" : "text-[14px]";
  const askMinH = size === "prominent" ? 44 : 40;
  const chipMinH = size === "prominent" ? 36 : 32;
  const chipText = size === "prominent" ? "text-[13px]" : "text-[12px]";
  const chipPad = size === "prominent" ? "px-3.5 py-2" : "px-3 py-1.5";

  // Chips visibility — when collapsibleChips is on, chips appear once
  // the input has focus or once a conversation has started. Otherwise
  // chips are always visible.
  const chipsVisible =
    !collapsibleChips || focused || msgs.length > 0 || q.length > 0;

  // Distinctive variant — accent-tinted background + small "Chekku AI"
  // badge top-left. Used on Home so AI reads as a different category
  // of surface from the regular floating cards below it.
  const wrapClass = distinctive
    ? "rounded-2xl bg-accent-soft border border-accent/25 p-3 pt-2.5"
    : "rounded-2xl bg-surface p-3 [box-shadow:var(--shadow-card)]";
  const inputBgClass = distinctive ? "bg-surface" : "bg-background";

  return (
    <div className={wrapClass}>
      {distinctive ? (
        <div className="mb-2 flex items-center gap-1.5 px-1">
          <SparkleIcon />
          <span className="text-[11px] font-semibold uppercase tracking-[0.08em] text-accent-strong">
            Chekku AI
          </span>
        </div>
      ) : null}
      <div className={`flex items-center gap-2.5 rounded-xl ${inputBgClass} py-1 pl-3.5 pr-1`}>
        {distinctive ? null : <SparkleIcon />}
        <input
          type="text"
          placeholder={placeholder ?? "Ask Chekku anything…"}
          value={q}
          onChange={(e) => setQ(e.target.value)}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          onKeyDown={(e) => e.key === "Enter" && ask()}
          className={`flex-1 bg-transparent ${inputPadY} ${inputText} outline-none`}
        />
        <button
          type="button"
          onClick={() => ask()}
          disabled={loading || !q.trim()}
          className={`rounded-lg bg-accent ${askPadX} ${askPadY} ${askText} font-semibold text-white disabled:opacity-40`}
          style={{ minHeight: askMinH }}
        >
          {loading ? "…" : "Ask"}
        </button>
      </div>

      {suggestions && suggestions.length > 0 && chipsVisible ? (
        <div className="mt-2.5 flex flex-wrap gap-2">
          {suggestions.map((s, i) => (
            <button
              key={i}
              type="button"
              // Use onMouseDown so the click fires before the input's
              // onBlur hides the chip — otherwise tapping a chip while
              // the input is focused races against the blur.
              onMouseDown={(e) => {
                e.preventDefault();
                void ask(s.question);
              }}
              disabled={loading}
              title={s.question}
              className={`rounded-full border border-accent/30 bg-accent-soft ${chipPad} ${chipText} font-semibold text-accent-strong transition-colors hover:bg-accent/15 disabled:opacity-40`}
              style={{ minHeight: chipMinH }}
            >
              {s.label}
            </button>
          ))}
        </div>
      ) : null}

      {msgs.length > 0 || loading ? (
        <div
          className="mt-3 max-h-72 space-y-2 overflow-y-auto pr-1"
          aria-live="polite"
        >
          {msgs.map((m, i) => (
            <div
              key={i}
              className={
                m.role === "user"
                  ? "ml-6 rounded-xl bg-surface-2 px-3 py-2.5 text-[13px]"
                  : "mr-6 rounded-xl border border-accent/20 bg-accent-soft/60 px-3 py-2.5 text-[13px]"
              }
            >
              <span className="mb-1 block text-[10px] font-semibold uppercase tracking-[0.06em] opacity-60">
                {m.role === "user" ? "You" : "Chekku"}
              </span>
              {m.role === "assistant" ? (
                <FormatAI text={m.content} />
              ) : (
                m.content
              )}
            </div>
          ))}
          {loading ? (
            <div className="mr-6 rounded-xl border border-accent/20 bg-accent-soft/60 px-3 py-2.5 text-[13px] text-accent-strong">
              <span className="mb-1 block text-[10px] font-semibold uppercase tracking-[0.06em] opacity-60">
                Chekku
              </span>
              <span className="animate-pulse">Thinking…</span>
            </div>
          ) : null}
          <div ref={tail} />
        </div>
      ) : null}
    </div>
  );
}

function SparkleIcon() {
  return (
    <svg
      width="22"
      height="22"
      viewBox="0 0 24 24"
      fill="none"
      className="shrink-0 text-accent"
      aria-hidden="true"
    >
      <path
        d="M12 3v3M12 18v3M3 12h3M18 12h3M5.5 5.5l2.1 2.1M16.4 16.4l2.1 2.1M5.5 18.5l2.1-2.1M16.4 7.6l2.1-2.1"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
      />
      <circle cx="12" cy="12" r="3" fill="currentColor" />
    </svg>
  );
}
